# Imports

In [1]:
import torch
from torch.utils.data import random_split, Dataset, DataLoader
import torch.nn as nn
import torch.nn.functional as F
from torchinfo import summary
from tqdm import tqdm
from sklearn.metrics import r2_score

# Constants

In [2]:
device = 'cuda'
batch_size = 1

# Dataset

In [3]:
class CompoundDataset(Dataset):
    def __init__(self, X: torch.tensor, Y: torch.tensor):
        super().__init__()
        self.X = X
        self.Y = Y
        self.shape = X.shape
        
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, index):
        return self.X[index], self.Y[index]

# Load the data

In [4]:
dataset = torch.load('data/dataset.pt')

C:\Users\agile\AppData\Local\Temp\ipykernel_37208\753396127.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  dataset = torch.load('data/dataset.pt')


# Split

In [5]:
# constants
DATASET_SIZE = len(dataset)  # Should be 499
TRAIN_RATIO = 0.9
TEST_RATIO = 1 - TRAIN_RATIO

# lengths of splits
train_len = int(TRAIN_RATIO * DATASET_SIZE)
test_len = DATASET_SIZE - train_len

torch.manual_seed(196)
train_dataset, test_dataset = random_split(dataset, [train_len, test_len])

Standardize

In [ ]:
train_idx = train_dataset.indices

X = dataset.X
Y = dataset.Y

x_mean = X[train_idx].mean(dim=0, keepdim=True)
x_std  = X[train_idx].std(dim=0, keepdim=True)

y_mean = Y[train_idx].mean(dim=0, keepdim=True)
y_std  = Y[train_idx].std(dim=0, keepdim=True)

eps = 1e-8

dataset.X = (X - x_mean) / (x_std + eps)
dataset.Y = (Y - y_mean) / (y_std + eps)    

In [16]:
print(X[:16])
print(Y[:16])

tensor([[2.0000e+00, 4.0000e+00, 2.0000e+00, 5.0000e-01, 7.0711e-01, 0.0000e+00],
        [8.0000e+00, 3.2000e+01, 3.2000e+01, 2.0000e+00, 1.0000e+00, 1.6000e+01],
        [2.8000e+01, 1.9800e+02, 3.4400e+02, 6.7619e+00, 1.5177e+00, 5.4611e+01],
        [4.8000e+01, 3.8400e+02, 7.6800e+02, 1.2000e+01, 2.1213e+00, 1.1378e+02],
        [6.2000e+01, 5.5400e+02, 1.2360e+03, 1.5319e+01, 2.3598e+00, 1.6123e+02],
        [5.4000e+01, 4.9000e+02, 1.1080e+03, 1.3319e+01, 2.0062e+00, 1.4227e+02],
        [6.2000e+01, 5.5400e+02, 1.2360e+03, 1.5319e+01, 2.3598e+00, 1.6123e+02],
        [1.8000e+01, 1.0800e+02, 1.6200e+02, 4.5000e+00, 1.2247e+00, 3.4172e+01],
        [8.6000e+01, 8.5000e+02, 2.1160e+03, 2.0944e+01, 2.9469e+00, 2.4445e+02],
        [2.0000e+00, 4.0000e+00, 2.0000e+00, 5.0000e-01, 7.0711e-01, 0.0000e+00],
        [8.0000e+01, 8.7200e+02, 2.3600e+03, 1.8022e+01, 2.6213e+00, 2.2434e+02],
        [8.0000e+00, 3.2000e+01, 3.2000e+01, 2.0000e+00, 1.0000e+00, 1.6000e+01],
        [2.0000e

Fit Diffs

In [1]:
precisions = [0.01, 0.1, 0.1, 0.01, 0.01, 0.1, 0.01, 0.1]
# precisions = [0.1, 0.1]
median_diffs = []
for col_idx in range(train_dataset.dataset.Y.shape[1]):
    column = train_dataset.dataset.Y[:, col_idx]
    column, _ = torch.sort(column)
    diffs = torch.diff(column)
    medain_diff = torch.median(diffs)
    if torch.isclose(medain_diff, torch.tensor(0.0)):
        medain_diff = precisions[col_idx]
    median_diffs.append(medain_diff)

median_diffs = torch.tensor(median_diffs)
print(median_diffs)

NameError: name 'train_dataset' is not defined

In [8]:
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)

# Model

In [9]:
class MIC(nn.Module):
    def __init__(self, input_features, output_features):
        super().__init__()
        self.fc1 = nn.Linear(input_features, 32)
        self.fc2 = nn.Linear(32, 64)
        self.fc3 = nn.Linear(64, 128)
        self.fc4 = nn.Linear(128, 64)
        self.fc5 = nn.Linear(64, 16)
        self.fc6 = nn.Linear(16, output_features)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        x = self.fc6(x)
        
        return x
        

In [10]:
model = MIC(train_dataset.dataset.X.shape[1], train_dataset.dataset.Y.shape[1])
summary(
    model,
    train_dataset.dataset.X.shape
)

Layer (type:depth-idx)                   Output Shape              Param #
MIC                                      [152, 2]                  --
├─Linear: 1-1                            [152, 32]                 224
├─Linear: 1-2                            [152, 64]                 2,112
├─Linear: 1-3                            [152, 128]                8,320
├─Linear: 1-4                            [152, 64]                 8,256
├─Linear: 1-5                            [152, 16]                 1,040
├─Linear: 1-6                            [152, 2]                  34
Total params: 19,986
Trainable params: 19,986
Non-trainable params: 0
Total mult-adds (M): 3.04
Input size (MB): 0.00
Forward/backward pass size (MB): 0.37
Params size (MB): 0.08
Estimated Total Size (MB): 0.46

# Loss Function

In [11]:
def mic_loss(median_diffs):
    eps = 1e-6
    
    def loss_function(predicted, true):
        diffs = torch.sqrt((true - predicted)**2 + 1e-3)

        md = median_diffs.to(diffs.device)
        scaled = diffs / (md + eps)

        loss = torch.log1p(scaled).mean()
        return loss
    
    return loss_function

# Training

In [12]:
# model, optimizer, and custom loss
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-1)
# criterion = mic_loss(median_diffs)
criterion = torch.nn.MSELoss(reduction='mean')

# training parameters
num_epochs = 500
loss_ot = [] # loss overtime

In [13]:
for epoch in range(num_epochs):
    # training on training dataset
    model.train()
    total_loss = 0

    pbar = tqdm(test_loader, desc=f"Epoch {epoch+1}/{num_epochs}")

    for inputs, targets in pbar:
        inputs = inputs.to(device)
        targets = targets.to(device)

        outputs = model(inputs)

        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        total_loss += loss.item()
        
    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}: Avg Training Loss = {avg_loss}")
    loss_ot.append(avg_loss)

Epoch 1/500: 100%|██████████| 16/16 [00:00<00:00, 180.22it/s]


Epoch 1: Avg Training Loss = 0.6397685709902469


Epoch 2/500: 100%|██████████| 16/16 [00:00<00:00, 430.27it/s]


Epoch 2: Avg Training Loss = 0.1937531540855108


Epoch 3/500: 100%|██████████| 16/16 [00:00<00:00, 766.85it/s]


Epoch 3: Avg Training Loss = 0.32759220469469097


Epoch 4/500: 100%|██████████| 16/16 [00:00<00:00, 378.45it/s]


Epoch 4: Avg Training Loss = 0.28517646846525807


Epoch 5/500: 100%|██████████| 16/16 [00:00<00:00, 469.56it/s]


Epoch 5: Avg Training Loss = 0.11008544792147244


Epoch 6/500: 100%|██████████| 16/16 [00:00<00:00, 583.72it/s]


Epoch 6: Avg Training Loss = 0.10236157849431038


Epoch 7/500: 100%|██████████| 16/16 [00:00<00:00, 342.07it/s]


Epoch 7: Avg Training Loss = 0.10208399232257814


Epoch 8/500: 100%|██████████| 16/16 [00:00<00:00, 576.38it/s]


Epoch 8: Avg Training Loss = 0.10312832500237752


Epoch 9/500: 100%|██████████| 16/16 [00:00<00:00, 459.31it/s]


Epoch 9: Avg Training Loss = 0.10106822218307678


Epoch 10/500: 100%|██████████| 16/16 [00:00<00:00, 541.44it/s]


Epoch 10: Avg Training Loss = 0.10335621780113262


Epoch 11/500: 100%|██████████| 16/16 [00:00<00:00, 570.90it/s]


Epoch 11: Avg Training Loss = 0.10458098675179131


Epoch 12/500: 100%|██████████| 16/16 [00:00<00:00, 596.47it/s]


Epoch 12: Avg Training Loss = 0.10327175807426958


Epoch 13/500: 100%|██████████| 16/16 [00:00<00:00, 548.49it/s]


Epoch 13: Avg Training Loss = 0.10571189720512313


Epoch 14/500: 100%|██████████| 16/16 [00:00<00:00, 547.85it/s]


Epoch 14: Avg Training Loss = 0.10102603757096563


Epoch 15/500: 100%|██████████| 16/16 [00:00<00:00, 660.18it/s]


Epoch 15: Avg Training Loss = 0.10284550841349889


Epoch 16/500: 100%|██████████| 16/16 [00:00<00:00, 575.16it/s]


Epoch 16: Avg Training Loss = 0.10129400035914253


Epoch 17/500: 100%|██████████| 16/16 [00:00<00:00, 429.79it/s]


Epoch 17: Avg Training Loss = 0.10257348903071355


Epoch 18/500: 100%|██████████| 16/16 [00:00<00:00, 524.74it/s]


Epoch 18: Avg Training Loss = 0.10622827078708831


Epoch 19/500: 100%|██████████| 16/16 [00:00<00:00, 530.89it/s]


Epoch 19: Avg Training Loss = 0.10391681926215396


Epoch 20/500: 100%|██████████| 16/16 [00:00<00:00, 675.19it/s]


Epoch 20: Avg Training Loss = 0.10465679312234416


Epoch 21/500: 100%|██████████| 16/16 [00:00<00:00, 574.71it/s]


Epoch 21: Avg Training Loss = 0.10391989909112453


Epoch 22/500: 100%|██████████| 16/16 [00:00<00:00, 589.87it/s]


Epoch 22: Avg Training Loss = 0.1011732576195808


Epoch 23/500: 100%|██████████| 16/16 [00:00<00:00, 555.70it/s]


Epoch 23: Avg Training Loss = 0.10327287401784868


Epoch 24/500: 100%|██████████| 16/16 [00:00<00:00, 538.95it/s]


Epoch 24: Avg Training Loss = 0.10557875163195764


Epoch 25/500: 100%|██████████| 16/16 [00:00<00:00, 548.37it/s]


Epoch 25: Avg Training Loss = 0.10305330488721237


Epoch 26/500: 100%|██████████| 16/16 [00:00<00:00, 567.54it/s]


Epoch 26: Avg Training Loss = 0.10155326886759962


Epoch 27/500: 100%|██████████| 16/16 [00:00<00:00, 592.56it/s]


Epoch 27: Avg Training Loss = 0.10835095834644402


Epoch 28/500: 100%|██████████| 16/16 [00:00<00:00, 401.39it/s]


Epoch 28: Avg Training Loss = 0.10413403400932164


Epoch 29/500: 100%|██████████| 16/16 [00:00<00:00, 648.01it/s]


Epoch 29: Avg Training Loss = 0.1068582532050855


Epoch 30/500: 100%|██████████| 16/16 [00:00<00:00, 588.61it/s]


Epoch 30: Avg Training Loss = 0.10260894116671647


Epoch 31/500: 100%|██████████| 16/16 [00:00<00:00, 552.57it/s]


Epoch 31: Avg Training Loss = 0.1064605257638237


Epoch 32/500: 100%|██████████| 16/16 [00:00<00:00, 668.24it/s]


Epoch 32: Avg Training Loss = 0.11230808044509853


Epoch 33/500: 100%|██████████| 16/16 [00:00<00:00, 533.89it/s]


Epoch 33: Avg Training Loss = 0.1206064474878504


Epoch 34/500: 100%|██████████| 16/16 [00:00<00:00, 617.21it/s]


Epoch 34: Avg Training Loss = 0.09996581211795702


Epoch 35/500: 100%|██████████| 16/16 [00:00<00:00, 573.81it/s]


Epoch 35: Avg Training Loss = 0.11699039154850385


Epoch 36/500: 100%|██████████| 16/16 [00:00<00:00, 592.03it/s]


Epoch 36: Avg Training Loss = 0.10236476753454875


Epoch 37/500: 100%|██████████| 16/16 [00:00<00:00, 438.73it/s]


Epoch 37: Avg Training Loss = 0.10564312092302476


Epoch 38/500: 100%|██████████| 16/16 [00:00<00:00, 452.37it/s]


Epoch 38: Avg Training Loss = 0.10351667794234612


Epoch 39/500: 100%|██████████| 16/16 [00:00<00:00, 555.52it/s]


Epoch 39: Avg Training Loss = 0.10675112914074869


Epoch 40/500: 100%|██████████| 16/16 [00:00<00:00, 651.58it/s]


Epoch 40: Avg Training Loss = 0.10373343702624827


Epoch 41/500: 100%|██████████| 16/16 [00:00<00:00, 577.48it/s]


Epoch 41: Avg Training Loss = 0.10256085629739306


Epoch 42/500: 100%|██████████| 16/16 [00:00<00:00, 599.78it/s]


Epoch 42: Avg Training Loss = 0.10346545153023566


Epoch 43/500: 100%|██████████| 16/16 [00:00<00:00, 552.46it/s]


Epoch 43: Avg Training Loss = 0.10454122081179829


Epoch 44/500: 100%|██████████| 16/16 [00:00<00:00, 602.95it/s]


Epoch 44: Avg Training Loss = 0.10162468583268278


Epoch 45/500: 100%|██████████| 16/16 [00:00<00:00, 508.96it/s]


Epoch 45: Avg Training Loss = 0.10270768546444528


Epoch 46/500: 100%|██████████| 16/16 [00:00<00:00, 573.75it/s]


Epoch 46: Avg Training Loss = 0.1032569462652592


Epoch 47/500: 100%|██████████| 16/16 [00:00<00:00, 415.02it/s]


Epoch 47: Avg Training Loss = 0.10295562070849187


Epoch 48/500: 100%|██████████| 16/16 [00:00<00:00, 576.40it/s]


Epoch 48: Avg Training Loss = 0.1056343011886758


Epoch 49/500: 100%|██████████| 16/16 [00:00<00:00, 577.58it/s]


Epoch 49: Avg Training Loss = 0.10517086685799501


Epoch 50/500: 100%|██████████| 16/16 [00:00<00:00, 482.34it/s]


Epoch 50: Avg Training Loss = 0.1033073869150351


Epoch 51/500: 100%|██████████| 16/16 [00:00<00:00, 534.33it/s]


Epoch 51: Avg Training Loss = 0.10429335237645052


Epoch 52/500: 100%|██████████| 16/16 [00:00<00:00, 530.01it/s]


Epoch 52: Avg Training Loss = 0.10303530066876727


Epoch 53/500: 100%|██████████| 16/16 [00:00<00:00, 583.27it/s]


Epoch 53: Avg Training Loss = 0.10388892763020362


Epoch 54/500: 100%|██████████| 16/16 [00:00<00:00, 529.17it/s]


Epoch 54: Avg Training Loss = 0.10688102784950067


Epoch 55/500: 100%|██████████| 16/16 [00:00<00:00, 623.92it/s]


Epoch 55: Avg Training Loss = 0.10388453675927047


Epoch 56/500: 100%|██████████| 16/16 [00:00<00:00, 491.57it/s]


Epoch 56: Avg Training Loss = 0.10354347710552461


Epoch 57/500: 100%|██████████| 16/16 [00:00<00:00, 539.19it/s]


Epoch 57: Avg Training Loss = 0.10396074446137338


Epoch 58/500: 100%|██████████| 16/16 [00:00<00:00, 543.27it/s]


Epoch 58: Avg Training Loss = 0.11039604265790652


Epoch 59/500: 100%|██████████| 16/16 [00:00<00:00, 556.50it/s]


Epoch 59: Avg Training Loss = 0.1010725369252374


Epoch 60/500: 100%|██████████| 16/16 [00:00<00:00, 575.96it/s]


Epoch 60: Avg Training Loss = 0.10557659389451146


Epoch 61/500: 100%|██████████| 16/16 [00:00<00:00, 597.20it/s]


Epoch 61: Avg Training Loss = 0.10416479348478948


Epoch 62/500: 100%|██████████| 16/16 [00:00<00:00, 606.13it/s]


Epoch 62: Avg Training Loss = 0.10545345193103832


Epoch 63/500: 100%|██████████| 16/16 [00:00<00:00, 591.64it/s]


Epoch 63: Avg Training Loss = 0.1020683200810762


Epoch 64/500: 100%|██████████| 16/16 [00:00<00:00, 543.17it/s]


Epoch 64: Avg Training Loss = 0.10985927786746555


Epoch 65/500: 100%|██████████| 16/16 [00:00<00:00, 459.56it/s]


Epoch 65: Avg Training Loss = 0.10271438953521497


Epoch 66/500: 100%|██████████| 16/16 [00:00<00:00, 510.50it/s]


Epoch 66: Avg Training Loss = 0.10445569099529702


Epoch 67/500: 100%|██████████| 16/16 [00:00<00:00, 536.60it/s]


Epoch 67: Avg Training Loss = 0.10752343901378267


Epoch 68/500: 100%|██████████| 16/16 [00:00<00:00, 620.70it/s]


Epoch 68: Avg Training Loss = 0.1004158389645026


Epoch 69/500: 100%|██████████| 16/16 [00:00<00:00, 695.52it/s]


Epoch 69: Avg Training Loss = 0.1081201496451874


Epoch 70/500: 100%|██████████| 16/16 [00:00<00:00, 595.65it/s]


Epoch 70: Avg Training Loss = 0.10375559724429075


Epoch 71/500: 100%|██████████| 16/16 [00:00<00:00, 607.75it/s]


Epoch 71: Avg Training Loss = 0.10357621770954746


Epoch 72/500: 100%|██████████| 16/16 [00:00<00:00, 601.68it/s]


Epoch 72: Avg Training Loss = 0.10639671159579474


Epoch 73/500: 100%|██████████| 16/16 [00:00<00:00, 589.65it/s]


Epoch 73: Avg Training Loss = 0.10388803979217567


Epoch 74/500: 100%|██████████| 16/16 [00:00<00:00, 612.57it/s]


Epoch 74: Avg Training Loss = 0.10558098968227997


Epoch 75/500: 100%|██████████| 16/16 [00:00<00:00, 344.19it/s]


Epoch 75: Avg Training Loss = 0.10401875509277862


Epoch 76/500: 100%|██████████| 16/16 [00:00<00:00, 614.10it/s]


Epoch 76: Avg Training Loss = 0.10587846482282176


Epoch 77/500: 100%|██████████| 16/16 [00:00<00:00, 576.29it/s]


Epoch 77: Avg Training Loss = 0.10772602621685057


Epoch 78/500: 100%|██████████| 16/16 [00:00<00:00, 637.35it/s]


Epoch 78: Avg Training Loss = 0.10286687095375623


Epoch 79/500: 100%|██████████| 16/16 [00:00<00:00, 602.47it/s]


Epoch 79: Avg Training Loss = 0.10272860929698628


Epoch 80/500: 100%|██████████| 16/16 [00:00<00:00, 598.64it/s]


Epoch 80: Avg Training Loss = 0.10551142717218574


Epoch 81/500: 100%|██████████| 16/16 [00:00<00:00, 592.46it/s]


Epoch 81: Avg Training Loss = 0.10181119405281018


Epoch 82/500: 100%|██████████| 16/16 [00:00<00:00, 588.15it/s]


Epoch 82: Avg Training Loss = 0.10372529178857803


Epoch 83/500: 100%|██████████| 16/16 [00:00<00:00, 544.77it/s]


Epoch 83: Avg Training Loss = 0.1016041667693678


Epoch 84/500: 100%|██████████| 16/16 [00:00<00:00, 556.54it/s]


Epoch 84: Avg Training Loss = 0.1033631172579001


Epoch 85/500: 100%|██████████| 16/16 [00:00<00:00, 319.86it/s]


Epoch 85: Avg Training Loss = 0.10299866799922551


Epoch 86/500: 100%|██████████| 16/16 [00:00<00:00, 602.98it/s]


Epoch 86: Avg Training Loss = 0.10629402240738273


Epoch 87/500: 100%|██████████| 16/16 [00:00<00:00, 555.25it/s]


Epoch 87: Avg Training Loss = 0.10356946768896545


Epoch 88/500: 100%|██████████| 16/16 [00:00<00:00, 566.79it/s]


Epoch 88: Avg Training Loss = 0.10877690124599372


Epoch 89/500: 100%|██████████| 16/16 [00:00<00:00, 643.37it/s]


Epoch 89: Avg Training Loss = 0.11032923899234875


Epoch 90/500: 100%|██████████| 16/16 [00:00<00:00, 579.61it/s]


Epoch 90: Avg Training Loss = 0.10231676883995533


Epoch 91/500: 100%|██████████| 16/16 [00:00<00:00, 621.35it/s]


Epoch 91: Avg Training Loss = 0.1036513333537561


Epoch 92/500: 100%|██████████| 16/16 [00:00<00:00, 569.53it/s]


Epoch 92: Avg Training Loss = 0.1043767399592873


Epoch 93/500: 100%|██████████| 16/16 [00:00<00:00, 504.62it/s]


Epoch 93: Avg Training Loss = 0.11103676065035603


Epoch 94/500: 100%|██████████| 16/16 [00:00<00:00, 393.31it/s]


Epoch 94: Avg Training Loss = 0.1023786604842719


Epoch 95/500: 100%|██████████| 16/16 [00:00<00:00, 578.87it/s]


Epoch 95: Avg Training Loss = 0.10583396184751216


Epoch 96/500: 100%|██████████| 16/16 [00:00<00:00, 650.05it/s]


Epoch 96: Avg Training Loss = 0.10323907884166521


Epoch 97/500: 100%|██████████| 16/16 [00:00<00:00, 575.18it/s]


Epoch 97: Avg Training Loss = 0.10688529125250437


Epoch 98/500: 100%|██████████| 16/16 [00:00<00:00, 622.80it/s]


Epoch 98: Avg Training Loss = 0.10596203552011181


Epoch 99/500: 100%|██████████| 16/16 [00:00<00:00, 578.50it/s]


Epoch 99: Avg Training Loss = 0.10343472566455603


Epoch 100/500: 100%|██████████| 16/16 [00:00<00:00, 596.96it/s]


Epoch 100: Avg Training Loss = 0.10754394150503419


Epoch 101/500: 100%|██████████| 16/16 [00:00<00:00, 587.39it/s]


Epoch 101: Avg Training Loss = 0.10248312562265817


Epoch 102/500: 100%|██████████| 16/16 [00:00<00:00, 498.83it/s]


Epoch 102: Avg Training Loss = 0.10524139273911715


Epoch 103/500: 100%|██████████| 16/16 [00:00<00:00, 550.98it/s]


Epoch 103: Avg Training Loss = 0.09999585140715628


Epoch 104/500: 100%|██████████| 16/16 [00:00<00:00, 369.33it/s]


Epoch 104: Avg Training Loss = 0.10779991606250405


Epoch 105/500: 100%|██████████| 16/16 [00:00<00:00, 586.43it/s]


Epoch 105: Avg Training Loss = 0.10217727183857385


Epoch 106/500: 100%|██████████| 16/16 [00:00<00:00, 527.98it/s]


Epoch 106: Avg Training Loss = 0.10568567507845514


Epoch 107/500: 100%|██████████| 16/16 [00:00<00:00, 437.56it/s]


Epoch 107: Avg Training Loss = 0.10469655235133626


Epoch 108/500: 100%|██████████| 16/16 [00:00<00:00, 574.89it/s]


Epoch 108: Avg Training Loss = 0.1027436738505083


Epoch 109/500: 100%|██████████| 16/16 [00:00<00:00, 595.30it/s]


Epoch 109: Avg Training Loss = 0.10639472397537354


Epoch 110/500: 100%|██████████| 16/16 [00:00<00:00, 576.81it/s]


Epoch 110: Avg Training Loss = 0.10471811707076781


Epoch 111/500: 100%|██████████| 16/16 [00:00<00:00, 661.94it/s]


Epoch 111: Avg Training Loss = 0.10433302050018135


Epoch 112/500: 100%|██████████| 16/16 [00:00<00:00, 595.69it/s]


Epoch 112: Avg Training Loss = 0.11141260888646631


Epoch 113/500: 100%|██████████| 16/16 [00:00<00:00, 399.24it/s]


Epoch 113: Avg Training Loss = 0.10420286836212173


Epoch 114/500: 100%|██████████| 16/16 [00:00<00:00, 462.94it/s]


Epoch 114: Avg Training Loss = 0.10856651679119643


Epoch 115/500: 100%|██████████| 16/16 [00:00<00:00, 576.24it/s]


Epoch 115: Avg Training Loss = 0.1041780944694491


Epoch 116/500: 100%|██████████| 16/16 [00:00<00:00, 582.66it/s]


Epoch 116: Avg Training Loss = 0.10695819562191472


Epoch 117/500: 100%|██████████| 16/16 [00:00<00:00, 683.83it/s]


Epoch 117: Avg Training Loss = 0.10209365408210193


Epoch 118/500: 100%|██████████| 16/16 [00:00<00:00, 503.60it/s]


Epoch 118: Avg Training Loss = 0.10100546276525539


Epoch 119/500: 100%|██████████| 16/16 [00:00<00:00, 563.27it/s]


Epoch 119: Avg Training Loss = 0.10347987716907964


Epoch 120/500: 100%|██████████| 16/16 [00:00<00:00, 537.16it/s]


Epoch 120: Avg Training Loss = 0.10347625366686021


Epoch 121/500: 100%|██████████| 16/16 [00:00<00:00, 586.14it/s]


Epoch 121: Avg Training Loss = 0.10211967956274748


Epoch 122/500: 100%|██████████| 16/16 [00:00<00:00, 655.47it/s]


Epoch 122: Avg Training Loss = 0.1040228096603909


Epoch 123/500: 100%|██████████| 16/16 [00:00<00:00, 397.52it/s]


Epoch 123: Avg Training Loss = 0.10575369435965139


Epoch 124/500: 100%|██████████| 16/16 [00:00<00:00, 602.13it/s]


Epoch 124: Avg Training Loss = 0.1096003779264934


Epoch 125/500: 100%|██████████| 16/16 [00:00<00:00, 587.87it/s]


Epoch 125: Avg Training Loss = 0.10169630036141504


Epoch 126/500: 100%|██████████| 16/16 [00:00<00:00, 493.22it/s]


Epoch 126: Avg Training Loss = 0.10421735114034485


Epoch 127/500: 100%|██████████| 16/16 [00:00<00:00, 672.70it/s]


Epoch 127: Avg Training Loss = 0.10207445108715225


Epoch 128/500: 100%|██████████| 16/16 [00:00<00:00, 552.47it/s]


Epoch 128: Avg Training Loss = 0.10982494261663626


Epoch 129/500: 100%|██████████| 16/16 [00:00<00:00, 566.76it/s]


Epoch 129: Avg Training Loss = 0.10457272148307632


Epoch 130/500: 100%|██████████| 16/16 [00:00<00:00, 496.89it/s]


Epoch 130: Avg Training Loss = 0.10507153221132125


Epoch 131/500: 100%|██████████| 16/16 [00:00<00:00, 475.97it/s]


Epoch 131: Avg Training Loss = 0.10201593803460984


Epoch 132/500: 100%|██████████| 16/16 [00:00<00:00, 345.26it/s]


Epoch 132: Avg Training Loss = 0.10273517588810886


Epoch 133/500: 100%|██████████| 16/16 [00:00<00:00, 584.60it/s]


Epoch 133: Avg Training Loss = 0.10310592216110843


Epoch 134/500: 100%|██████████| 16/16 [00:00<00:00, 587.73it/s]


Epoch 134: Avg Training Loss = 0.10292871540193171


Epoch 135/500: 100%|██████████| 16/16 [00:00<00:00, 474.64it/s]


Epoch 135: Avg Training Loss = 0.10225777207490276


Epoch 136/500: 100%|██████████| 16/16 [00:00<00:00, 465.44it/s]


Epoch 136: Avg Training Loss = 0.10255902852205669


Epoch 137/500: 100%|██████████| 16/16 [00:00<00:00, 611.38it/s]


Epoch 137: Avg Training Loss = 0.10253762157962602


Epoch 138/500: 100%|██████████| 16/16 [00:00<00:00, 592.57it/s]


Epoch 138: Avg Training Loss = 0.10222909583107513


Epoch 139/500: 100%|██████████| 16/16 [00:00<00:00, 535.25it/s]


Epoch 139: Avg Training Loss = 0.10449850055224755


Epoch 140/500: 100%|██████████| 16/16 [00:00<00:00, 597.59it/s]


Epoch 140: Avg Training Loss = 0.10544259254546727


Epoch 141/500: 100%|██████████| 16/16 [00:00<00:00, 372.38it/s]


Epoch 141: Avg Training Loss = 0.10674692268538125


Epoch 142/500: 100%|██████████| 16/16 [00:00<00:00, 571.23it/s]


Epoch 142: Avg Training Loss = 0.10306049792972558


Epoch 143/500: 100%|██████████| 16/16 [00:00<00:00, 490.58it/s]


Epoch 143: Avg Training Loss = 0.10567099275067449


Epoch 144/500: 100%|██████████| 16/16 [00:00<00:00, 520.17it/s]


Epoch 144: Avg Training Loss = 0.1032883751699153


Epoch 145/500: 100%|██████████| 16/16 [00:00<00:00, 575.41it/s]


Epoch 145: Avg Training Loss = 0.10381282849566024


Epoch 146/500: 100%|██████████| 16/16 [00:00<00:00, 550.23it/s]


Epoch 146: Avg Training Loss = 0.10567056620493531


Epoch 147/500: 100%|██████████| 16/16 [00:00<00:00, 599.26it/s]


Epoch 147: Avg Training Loss = 0.10470890533179045


Epoch 148/500: 100%|██████████| 16/16 [00:00<00:00, 569.16it/s]


Epoch 148: Avg Training Loss = 0.10412225581924706


Epoch 149/500: 100%|██████████| 16/16 [00:00<00:00, 459.60it/s]


Epoch 149: Avg Training Loss = 0.10754935958367937


Epoch 150/500: 100%|██████████| 16/16 [00:00<00:00, 513.48it/s]


Epoch 150: Avg Training Loss = 0.10135330385802423


Epoch 151/500: 100%|██████████| 16/16 [00:00<00:00, 335.57it/s]


Epoch 151: Avg Training Loss = 0.10815391784040805


Epoch 152/500: 100%|██████████| 16/16 [00:00<00:00, 658.48it/s]


Epoch 152: Avg Training Loss = 0.10943457651335527


Epoch 153/500: 100%|██████████| 16/16 [00:00<00:00, 643.75it/s]


Epoch 153: Avg Training Loss = 0.10128197019152782


Epoch 154/500: 100%|██████████| 16/16 [00:00<00:00, 536.82it/s]


Epoch 154: Avg Training Loss = 0.10376682203701314


Epoch 155/500: 100%|██████████| 16/16 [00:00<00:00, 619.85it/s]


Epoch 155: Avg Training Loss = 0.10713350972818102


Epoch 156/500: 100%|██████████| 16/16 [00:00<00:00, 606.74it/s]


Epoch 156: Avg Training Loss = 0.1016196746050435


Epoch 157/500: 100%|██████████| 16/16 [00:00<00:00, 546.41it/s]


Epoch 157: Avg Training Loss = 0.10484149422058288


Epoch 158/500: 100%|██████████| 16/16 [00:00<00:00, 566.82it/s]


Epoch 158: Avg Training Loss = 0.10614718539256822


Epoch 159/500: 100%|██████████| 16/16 [00:00<00:00, 553.98it/s]


Epoch 159: Avg Training Loss = 0.10829144932658356


Epoch 160/500: 100%|██████████| 16/16 [00:00<00:00, 352.61it/s]


Epoch 160: Avg Training Loss = 0.10720022682867505


Epoch 161/500: 100%|██████████| 16/16 [00:00<00:00, 611.55it/s]


Epoch 161: Avg Training Loss = 0.10283992932561566


Epoch 162/500: 100%|██████████| 16/16 [00:00<00:00, 578.88it/s]


Epoch 162: Avg Training Loss = 0.1038132727091365


Epoch 163/500: 100%|██████████| 16/16 [00:00<00:00, 556.02it/s]


Epoch 163: Avg Training Loss = 0.10496964686385848


Epoch 164/500: 100%|██████████| 16/16 [00:00<00:00, 597.42it/s]


Epoch 164: Avg Training Loss = 0.10230665322502747


Epoch 165/500: 100%|██████████| 16/16 [00:00<00:00, 574.73it/s]


Epoch 165: Avg Training Loss = 0.1029483480105067


Epoch 166/500: 100%|██████████| 16/16 [00:00<00:00, 514.17it/s]


Epoch 166: Avg Training Loss = 0.10579912672641084


Epoch 167/500: 100%|██████████| 16/16 [00:00<00:00, 561.21it/s]


Epoch 167: Avg Training Loss = 0.10340121110408183


Epoch 168/500: 100%|██████████| 16/16 [00:00<00:00, 553.27it/s]


Epoch 168: Avg Training Loss = 0.10611971703303211


Epoch 169/500: 100%|██████████| 16/16 [00:00<00:00, 577.50it/s]


Epoch 169: Avg Training Loss = 0.1117640825207619


Epoch 170/500: 100%|██████████| 16/16 [00:00<00:00, 316.12it/s]


Epoch 170: Avg Training Loss = 0.1061763782875941


Epoch 171/500: 100%|██████████| 16/16 [00:00<00:00, 449.36it/s]


Epoch 171: Avg Training Loss = 0.10308841439237927


Epoch 172/500: 100%|██████████| 16/16 [00:00<00:00, 628.42it/s]


Epoch 172: Avg Training Loss = 0.103004028691965


Epoch 173/500: 100%|██████████| 16/16 [00:00<00:00, 578.96it/s]


Epoch 173: Avg Training Loss = 0.11191252446459497


Epoch 174/500: 100%|██████████| 16/16 [00:00<00:00, 570.39it/s]


Epoch 174: Avg Training Loss = 0.11108344456400066


Epoch 175/500: 100%|██████████| 16/16 [00:00<00:00, 594.24it/s]


Epoch 175: Avg Training Loss = 0.10577021602212507


Epoch 176/500: 100%|██████████| 16/16 [00:00<00:00, 595.99it/s]


Epoch 176: Avg Training Loss = 0.11017053059357054


Epoch 177/500: 100%|██████████| 16/16 [00:00<00:00, 550.23it/s]


Epoch 177: Avg Training Loss = 0.10438000628560343


Epoch 178/500: 100%|██████████| 16/16 [00:00<00:00, 522.22it/s]


Epoch 178: Avg Training Loss = 0.10607228685608681


Epoch 179/500: 100%|██████████| 16/16 [00:00<00:00, 549.54it/s]


Epoch 179: Avg Training Loss = 0.10296318852616583


Epoch 180/500: 100%|██████████| 16/16 [00:00<00:00, 328.59it/s]


Epoch 180: Avg Training Loss = 0.1025137285811498


Epoch 181/500: 100%|██████████| 16/16 [00:00<00:00, 489.85it/s]


Epoch 181: Avg Training Loss = 0.106463931966573


Epoch 182/500: 100%|██████████| 16/16 [00:00<00:00, 587.25it/s]


Epoch 182: Avg Training Loss = 0.1160167604136993


Epoch 183/500: 100%|██████████| 16/16 [00:00<00:00, 536.59it/s]


Epoch 183: Avg Training Loss = 0.1095086316961576


Epoch 184/500: 100%|██████████| 16/16 [00:00<00:00, 590.35it/s]


Epoch 184: Avg Training Loss = 0.10383670995532371


Epoch 185/500: 100%|██████████| 16/16 [00:00<00:00, 574.44it/s]


Epoch 185: Avg Training Loss = 0.10469536329893504


Epoch 186/500: 100%|██████████| 16/16 [00:00<00:00, 582.25it/s]


Epoch 186: Avg Training Loss = 0.10458179492065135


Epoch 187/500: 100%|██████████| 16/16 [00:00<00:00, 585.86it/s]


Epoch 187: Avg Training Loss = 0.10229510575642481


Epoch 188/500: 100%|██████████| 16/16 [00:00<00:00, 555.38it/s]


Epoch 188: Avg Training Loss = 0.10768739766824771


Epoch 189/500: 100%|██████████| 16/16 [00:00<00:00, 520.50it/s]


Epoch 189: Avg Training Loss = 0.11311573951559908


Epoch 190/500: 100%|██████████| 16/16 [00:00<00:00, 628.91it/s]


Epoch 190: Avg Training Loss = 0.10498208697775707


Epoch 191/500: 100%|██████████| 16/16 [00:00<00:00, 336.20it/s]


Epoch 191: Avg Training Loss = 0.10464534420958337


Epoch 192/500: 100%|██████████| 16/16 [00:00<00:00, 389.28it/s]


Epoch 192: Avg Training Loss = 0.10173075185979114


Epoch 193/500: 100%|██████████| 16/16 [00:00<00:00, 551.51it/s]


Epoch 193: Avg Training Loss = 0.10375214814591933


Epoch 194/500: 100%|██████████| 16/16 [00:00<00:00, 582.69it/s]


Epoch 194: Avg Training Loss = 0.10391070126720212


Epoch 195/500: 100%|██████████| 16/16 [00:00<00:00, 544.39it/s]


Epoch 195: Avg Training Loss = 0.10371552046169252


Epoch 196/500: 100%|██████████| 16/16 [00:00<00:00, 604.72it/s]


Epoch 196: Avg Training Loss = 0.10244580725317493


Epoch 197/500: 100%|██████████| 16/16 [00:00<00:00, 559.14it/s]


Epoch 197: Avg Training Loss = 0.1024911411873558


Epoch 198/500: 100%|██████████| 16/16 [00:00<00:00, 674.52it/s]


Epoch 198: Avg Training Loss = 0.10494397139614996


Epoch 199/500: 100%|██████████| 16/16 [00:00<00:00, 498.94it/s]


Epoch 199: Avg Training Loss = 0.10184407280758023


Epoch 200/500: 100%|██████████| 16/16 [00:00<00:00, 342.57it/s]


Epoch 200: Avg Training Loss = 0.1050216555595398


Epoch 201/500: 100%|██████████| 16/16 [00:00<00:00, 551.12it/s]


Epoch 201: Avg Training Loss = 0.10593477107913178


Epoch 202/500: 100%|██████████| 16/16 [00:00<00:00, 502.73it/s]


Epoch 202: Avg Training Loss = 0.10479977463974673


Epoch 203/500: 100%|██████████| 16/16 [00:00<00:00, 490.13it/s]


Epoch 203: Avg Training Loss = 0.10474068194846897


Epoch 204/500: 100%|██████████| 16/16 [00:00<00:00, 469.70it/s]


Epoch 204: Avg Training Loss = 0.10368224237497677


Epoch 205/500: 100%|██████████| 16/16 [00:00<00:00, 649.91it/s]


Epoch 205: Avg Training Loss = 0.1030147421064184


Epoch 206/500: 100%|██████████| 16/16 [00:00<00:00, 539.04it/s]


Epoch 206: Avg Training Loss = 0.10586481125039213


Epoch 207/500: 100%|██████████| 16/16 [00:00<00:00, 553.62it/s]


Epoch 207: Avg Training Loss = 0.10295825298218166


Epoch 208/500: 100%|██████████| 16/16 [00:00<00:00, 558.02it/s]


Epoch 208: Avg Training Loss = 0.10487366886809468


Epoch 209/500: 100%|██████████| 16/16 [00:00<00:00, 540.70it/s]


Epoch 209: Avg Training Loss = 0.1139118627179414


Epoch 210/500: 100%|██████████| 16/16 [00:00<00:00, 543.51it/s]


Epoch 210: Avg Training Loss = 0.10255478382768


Epoch 211/500: 100%|██████████| 16/16 [00:00<00:00, 344.90it/s]


Epoch 211: Avg Training Loss = 0.1034082607640063


Epoch 212/500: 100%|██████████| 16/16 [00:00<00:00, 561.74it/s]


Epoch 212: Avg Training Loss = 0.10304988309850588


Epoch 213/500: 100%|██████████| 16/16 [00:00<00:00, 518.90it/s]


Epoch 213: Avg Training Loss = 0.1043530293082928


Epoch 214/500: 100%|██████████| 16/16 [00:00<00:00, 497.56it/s]


Epoch 214: Avg Training Loss = 0.10340738060938962


Epoch 215/500: 100%|██████████| 16/16 [00:00<00:00, 489.70it/s]


Epoch 215: Avg Training Loss = 0.10452783628202536


Epoch 216/500: 100%|██████████| 16/16 [00:00<00:00, 551.17it/s]


Epoch 216: Avg Training Loss = 0.10412750836900052


Epoch 217/500: 100%|██████████| 16/16 [00:00<00:00, 631.82it/s]


Epoch 217: Avg Training Loss = 0.10364642388680402


Epoch 218/500: 100%|██████████| 16/16 [00:00<00:00, 549.71it/s]


Epoch 218: Avg Training Loss = 0.10236881333677207


Epoch 219/500: 100%|██████████| 16/16 [00:00<00:00, 531.76it/s]


Epoch 219: Avg Training Loss = 0.10253044854685225


Epoch 220/500: 100%|██████████| 16/16 [00:00<00:00, 670.57it/s]


Epoch 220: Avg Training Loss = 0.10300600158927195


Epoch 221/500: 100%|██████████| 16/16 [00:00<00:00, 343.49it/s]


Epoch 221: Avg Training Loss = 0.10563579404397923


Epoch 222/500: 100%|██████████| 16/16 [00:00<00:00, 504.75it/s]


Epoch 222: Avg Training Loss = 0.10271871580249246


Epoch 223/500: 100%|██████████| 16/16 [00:00<00:00, 507.22it/s]


Epoch 223: Avg Training Loss = 0.10235488477765638


Epoch 224/500: 100%|██████████| 16/16 [00:00<00:00, 572.51it/s]


Epoch 224: Avg Training Loss = 0.10532777438707211


Epoch 225/500: 100%|██████████| 16/16 [00:00<00:00, 524.01it/s]


Epoch 225: Avg Training Loss = 0.10123477136606679


Epoch 226/500: 100%|██████████| 16/16 [00:00<00:00, 563.62it/s]


Epoch 226: Avg Training Loss = 0.10515254500376828


Epoch 227/500: 100%|██████████| 16/16 [00:00<00:00, 581.38it/s]


Epoch 227: Avg Training Loss = 0.10436382791136994


Epoch 228/500: 100%|██████████| 16/16 [00:00<00:00, 544.61it/s]


Epoch 228: Avg Training Loss = 0.10154783828457926


Epoch 229/500: 100%|██████████| 16/16 [00:00<00:00, 512.08it/s]


Epoch 229: Avg Training Loss = 0.10242693022112637


Epoch 230/500: 100%|██████████| 16/16 [00:00<00:00, 435.90it/s]


Epoch 230: Avg Training Loss = 0.10327561473583474


Epoch 231/500: 100%|██████████| 16/16 [00:00<00:00, 418.98it/s]


Epoch 231: Avg Training Loss = 0.1040879530722604


Epoch 232/500: 100%|██████████| 16/16 [00:00<00:00, 552.33it/s]


Epoch 232: Avg Training Loss = 0.10573376641225289


Epoch 233/500: 100%|██████████| 16/16 [00:00<00:00, 576.89it/s]


Epoch 233: Avg Training Loss = 0.10270105628296733


Epoch 234/500: 100%|██████████| 16/16 [00:00<00:00, 570.77it/s]


Epoch 234: Avg Training Loss = 0.10255250918185886


Epoch 235/500: 100%|██████████| 16/16 [00:00<00:00, 598.42it/s]


Epoch 235: Avg Training Loss = 0.1016383614829358


Epoch 236/500: 100%|██████████| 16/16 [00:00<00:00, 573.27it/s]


Epoch 236: Avg Training Loss = 0.10260206614347066


Epoch 237/500: 100%|██████████| 16/16 [00:00<00:00, 505.99it/s]


Epoch 237: Avg Training Loss = 0.10305597520816852


Epoch 238/500: 100%|██████████| 16/16 [00:00<00:00, 539.74it/s]


Epoch 238: Avg Training Loss = 0.10423884092939689


Epoch 239/500: 100%|██████████| 16/16 [00:00<00:00, 297.32it/s]


Epoch 239: Avg Training Loss = 0.10334237653981238


Epoch 240/500: 100%|██████████| 16/16 [00:00<00:00, 451.09it/s]


Epoch 240: Avg Training Loss = 0.10523366399438065


Epoch 241/500: 100%|██████████| 16/16 [00:00<00:00, 498.31it/s]


Epoch 241: Avg Training Loss = 0.105582951239365


Epoch 242/500: 100%|██████████| 16/16 [00:00<00:00, 555.11it/s]


Epoch 242: Avg Training Loss = 0.10265802249641102


Epoch 243/500: 100%|██████████| 16/16 [00:00<00:00, 511.60it/s]


Epoch 243: Avg Training Loss = 0.10821096894933897


Epoch 244/500: 100%|██████████| 16/16 [00:00<00:00, 564.85it/s]


Epoch 244: Avg Training Loss = 0.10844863369129598


Epoch 245/500: 100%|██████████| 16/16 [00:00<00:00, 504.54it/s]


Epoch 245: Avg Training Loss = 0.1069277367718956


Epoch 246/500: 100%|██████████| 16/16 [00:00<00:00, 570.99it/s]


Epoch 246: Avg Training Loss = 0.10917971250327195


Epoch 247/500: 100%|██████████| 16/16 [00:00<00:00, 637.50it/s]


Epoch 247: Avg Training Loss = 0.10378488816101761


Epoch 248/500: 100%|██████████| 16/16 [00:00<00:00, 460.62it/s]


Epoch 248: Avg Training Loss = 0.10286886727108675


Epoch 249/500: 100%|██████████| 16/16 [00:00<00:00, 373.65it/s]


Epoch 249: Avg Training Loss = 0.10219933322685607


Epoch 250/500: 100%|██████████| 16/16 [00:00<00:00, 551.59it/s]


Epoch 250: Avg Training Loss = 0.10431550991009264


Epoch 251/500: 100%|██████████| 16/16 [00:00<00:00, 512.29it/s]


Epoch 251: Avg Training Loss = 0.10534453329027575


Epoch 252/500: 100%|██████████| 16/16 [00:00<00:00, 508.81it/s]


Epoch 252: Avg Training Loss = 0.10333885997533798


Epoch 253/500: 100%|██████████| 16/16 [00:00<00:00, 537.08it/s]


Epoch 253: Avg Training Loss = 0.10428725309012567


Epoch 254/500: 100%|██████████| 16/16 [00:00<00:00, 643.47it/s]


Epoch 254: Avg Training Loss = 0.10550300760523361


Epoch 255/500: 100%|██████████| 16/16 [00:00<00:00, 622.23it/s]


Epoch 255: Avg Training Loss = 0.10296900603262817


Epoch 256/500: 100%|██████████| 16/16 [00:00<00:00, 716.98it/s]


Epoch 256: Avg Training Loss = 0.10743337464244927


Epoch 257/500: 100%|██████████| 16/16 [00:00<00:00, 664.63it/s]


Epoch 257: Avg Training Loss = 0.10548830347354798


Epoch 258/500: 100%|██████████| 16/16 [00:00<00:00, 619.07it/s]


Epoch 258: Avg Training Loss = 0.1026943737969679


Epoch 259/500: 100%|██████████| 16/16 [00:00<00:00, 763.22it/s]


Epoch 259: Avg Training Loss = 0.1029808979262324


Epoch 260/500: 100%|██████████| 16/16 [00:00<00:00, 689.13it/s]


Epoch 260: Avg Training Loss = 0.10392891166403014


Epoch 261/500: 100%|██████████| 16/16 [00:00<00:00, 671.16it/s]


Epoch 261: Avg Training Loss = 0.10544747546972598


Epoch 262/500: 100%|██████████| 16/16 [00:00<00:00, 660.09it/s]


Epoch 262: Avg Training Loss = 0.10373255462550066


Epoch 263/500: 100%|██████████| 16/16 [00:00<00:00, 380.75it/s]


Epoch 263: Avg Training Loss = 0.10679135167532984


Epoch 264/500: 100%|██████████| 16/16 [00:00<00:00, 622.76it/s]


Epoch 264: Avg Training Loss = 0.11311705059864942


Epoch 265/500: 100%|██████████| 16/16 [00:00<00:00, 559.00it/s]


Epoch 265: Avg Training Loss = 0.10009614504216348


Epoch 266/500: 100%|██████████| 16/16 [00:00<00:00, 591.69it/s]


Epoch 266: Avg Training Loss = 0.1035755986950415


Epoch 267/500: 100%|██████████| 16/16 [00:00<00:00, 522.85it/s]


Epoch 267: Avg Training Loss = 0.10499658657457023


Epoch 268/500: 100%|██████████| 16/16 [00:00<00:00, 537.15it/s]


Epoch 268: Avg Training Loss = 0.1038368466474554


Epoch 269/500: 100%|██████████| 16/16 [00:00<00:00, 631.49it/s]


Epoch 269: Avg Training Loss = 0.10326922706821386


Epoch 270/500: 100%|██████████| 16/16 [00:00<00:00, 791.42it/s]


Epoch 270: Avg Training Loss = 0.10195149067679748


Epoch 271/500: 100%|██████████| 16/16 [00:00<00:00, 700.99it/s]


Epoch 271: Avg Training Loss = 0.10494871485485312


Epoch 272/500: 100%|██████████| 16/16 [00:00<00:00, 576.52it/s]


Epoch 272: Avg Training Loss = 0.11027809254386846


Epoch 273/500: 100%|██████████| 16/16 [00:00<00:00, 641.06it/s]


Epoch 273: Avg Training Loss = 0.11326287254033719


Epoch 274/500: 100%|██████████| 16/16 [00:00<00:00, 620.99it/s]


Epoch 274: Avg Training Loss = 0.1060990810750381


Epoch 275/500: 100%|██████████| 16/16 [00:00<00:00, 620.21it/s]


Epoch 275: Avg Training Loss = 0.10403357385931646


Epoch 276/500: 100%|██████████| 16/16 [00:00<00:00, 790.15it/s]


Epoch 276: Avg Training Loss = 0.10576943017761498


Epoch 277/500: 100%|██████████| 16/16 [00:00<00:00, 429.47it/s]


Epoch 277: Avg Training Loss = 0.10248179829624646


Epoch 278/500: 100%|██████████| 16/16 [00:00<00:00, 680.38it/s]


Epoch 278: Avg Training Loss = 0.11002884119036882


Epoch 279/500: 100%|██████████| 16/16 [00:00<00:00, 599.15it/s]


Epoch 279: Avg Training Loss = 0.10452052230453666


Epoch 280/500: 100%|██████████| 16/16 [00:00<00:00, 564.94it/s]


Epoch 280: Avg Training Loss = 0.10443738809622385


Epoch 281/500: 100%|██████████| 16/16 [00:00<00:00, 590.70it/s]


Epoch 281: Avg Training Loss = 0.10310522814774338


Epoch 282/500: 100%|██████████| 16/16 [00:00<00:00, 603.20it/s]


Epoch 282: Avg Training Loss = 0.10745981195941567


Epoch 283/500: 100%|██████████| 16/16 [00:00<00:00, 734.59it/s]


Epoch 283: Avg Training Loss = 0.10780466698548373


Epoch 284/500: 100%|██████████| 16/16 [00:00<00:00, 612.20it/s]


Epoch 284: Avg Training Loss = 0.10458318861749243


Epoch 285/500: 100%|██████████| 16/16 [00:00<00:00, 660.10it/s]


Epoch 285: Avg Training Loss = 0.10364100819124895


Epoch 286/500: 100%|██████████| 16/16 [00:00<00:00, 675.17it/s]


Epoch 286: Avg Training Loss = 0.1027787303113762


Epoch 287/500: 100%|██████████| 16/16 [00:00<00:00, 685.13it/s]


Epoch 287: Avg Training Loss = 0.10435776935671182


Epoch 288/500: 100%|██████████| 16/16 [00:00<00:00, 702.47it/s]


Epoch 288: Avg Training Loss = 0.10101151685504352


Epoch 289/500: 100%|██████████| 16/16 [00:00<00:00, 607.38it/s]


Epoch 289: Avg Training Loss = 0.1028366484131445


Epoch 290/500: 100%|██████████| 16/16 [00:00<00:00, 491.23it/s]


Epoch 290: Avg Training Loss = 0.11045611460747964


Epoch 291/500: 100%|██████████| 16/16 [00:00<00:00, 534.41it/s]


Epoch 291: Avg Training Loss = 0.1025266052388093


Epoch 292/500: 100%|██████████| 16/16 [00:00<00:00, 568.20it/s]


Epoch 292: Avg Training Loss = 0.10309974471216693


Epoch 293/500: 100%|██████████| 16/16 [00:00<00:00, 558.09it/s]


Epoch 293: Avg Training Loss = 0.10222420452491325


Epoch 294/500: 100%|██████████| 16/16 [00:00<00:00, 622.58it/s]


Epoch 294: Avg Training Loss = 0.10266126340309925


Epoch 295/500: 100%|██████████| 16/16 [00:00<00:00, 664.60it/s]


Epoch 295: Avg Training Loss = 0.10840249795685797


Epoch 296/500: 100%|██████████| 16/16 [00:00<00:00, 617.54it/s]


Epoch 296: Avg Training Loss = 0.1083405139746473


Epoch 297/500: 100%|██████████| 16/16 [00:00<00:00, 650.51it/s]


Epoch 297: Avg Training Loss = 0.10541351420311805


Epoch 298/500: 100%|██████████| 16/16 [00:00<00:00, 599.31it/s]


Epoch 298: Avg Training Loss = 0.10797102686346453


Epoch 299/500: 100%|██████████| 16/16 [00:00<00:00, 598.20it/s]


Epoch 299: Avg Training Loss = 0.10213594423497424


Epoch 300/500: 100%|██████████| 16/16 [00:00<00:00, 699.22it/s]


Epoch 300: Avg Training Loss = 0.10785336384330602


Epoch 301/500: 100%|██████████| 16/16 [00:00<00:00, 594.91it/s]


Epoch 301: Avg Training Loss = 0.10383098219137858


Epoch 302/500: 100%|██████████| 16/16 [00:00<00:00, 601.04it/s]


Epoch 302: Avg Training Loss = 0.10196190163054887


Epoch 303/500: 100%|██████████| 16/16 [00:00<00:00, 643.42it/s]


Epoch 303: Avg Training Loss = 0.10549860535299077


Epoch 304/500: 100%|██████████| 16/16 [00:00<00:00, 448.80it/s]


Epoch 304: Avg Training Loss = 0.10657029412686825


Epoch 305/500: 100%|██████████| 16/16 [00:00<00:00, 561.87it/s]


Epoch 305: Avg Training Loss = 0.10575446294730201


Epoch 306/500: 100%|██████████| 16/16 [00:00<00:00, 663.97it/s]


Epoch 306: Avg Training Loss = 0.10589144592556883


Epoch 307/500: 100%|██████████| 16/16 [00:00<00:00, 675.19it/s]


Epoch 307: Avg Training Loss = 0.10356215954593875


Epoch 308/500: 100%|██████████| 16/16 [00:00<00:00, 704.70it/s]


Epoch 308: Avg Training Loss = 0.10395582732470597


Epoch 309/500: 100%|██████████| 16/16 [00:00<00:00, 662.16it/s]


Epoch 309: Avg Training Loss = 0.10455423089511254


Epoch 310/500: 100%|██████████| 16/16 [00:00<00:00, 642.21it/s]


Epoch 310: Avg Training Loss = 0.10174353513866663


Epoch 311/500: 100%|██████████| 16/16 [00:00<00:00, 753.12it/s]


Epoch 311: Avg Training Loss = 0.10371562430415959


Epoch 312/500: 100%|██████████| 16/16 [00:00<00:00, 624.37it/s]


Epoch 312: Avg Training Loss = 0.1091147351955228


Epoch 313/500: 100%|██████████| 16/16 [00:00<00:00, 734.18it/s]


Epoch 313: Avg Training Loss = 0.10248292155344696


Epoch 314/500: 100%|██████████| 16/16 [00:00<00:00, 630.54it/s]


Epoch 314: Avg Training Loss = 0.10236310890382704


Epoch 315/500: 100%|██████████| 16/16 [00:00<00:00, 648.75it/s]


Epoch 315: Avg Training Loss = 0.10335091296035577


Epoch 316/500: 100%|██████████| 16/16 [00:00<00:00, 735.22it/s]


Epoch 316: Avg Training Loss = 0.10462966514751315


Epoch 317/500: 100%|██████████| 16/16 [00:00<00:00, 398.12it/s]


Epoch 317: Avg Training Loss = 0.11181461960351204


Epoch 318/500: 100%|██████████| 16/16 [00:00<00:00, 639.98it/s]


Epoch 318: Avg Training Loss = 0.10631115093608112


Epoch 319/500: 100%|██████████| 16/16 [00:00<00:00, 599.81it/s]


Epoch 319: Avg Training Loss = 0.10262476033805047


Epoch 320/500: 100%|██████████| 16/16 [00:00<00:00, 640.17it/s]


Epoch 320: Avg Training Loss = 0.10711103075129144


Epoch 321/500: 100%|██████████| 16/16 [00:00<00:00, 710.78it/s]


Epoch 321: Avg Training Loss = 0.10157186310628757


Epoch 322/500: 100%|██████████| 16/16 [00:00<00:00, 616.19it/s]


Epoch 322: Avg Training Loss = 0.1097501378013369


Epoch 323/500: 100%|██████████| 16/16 [00:00<00:00, 598.47it/s]


Epoch 323: Avg Training Loss = 0.10073892251752756


Epoch 324/500: 100%|██████████| 16/16 [00:00<00:00, 653.90it/s]


Epoch 324: Avg Training Loss = 0.1021674229106044


Epoch 325/500: 100%|██████████| 16/16 [00:00<00:00, 701.69it/s]


Epoch 325: Avg Training Loss = 0.10445165913552046


Epoch 326/500: 100%|██████████| 16/16 [00:00<00:00, 606.37it/s]


Epoch 326: Avg Training Loss = 0.10318239980979878


Epoch 327/500: 100%|██████████| 16/16 [00:00<00:00, 663.24it/s]


Epoch 327: Avg Training Loss = 0.10419152781148167


Epoch 328/500: 100%|██████████| 16/16 [00:00<00:00, 737.62it/s]


Epoch 328: Avg Training Loss = 0.10430277818266083


Epoch 329/500: 100%|██████████| 16/16 [00:00<00:00, 699.03it/s]


Epoch 329: Avg Training Loss = 0.1061809365363682


Epoch 330/500: 100%|██████████| 16/16 [00:00<00:00, 472.24it/s]


Epoch 330: Avg Training Loss = 0.10623570137164172


Epoch 331/500: 100%|██████████| 16/16 [00:00<00:00, 497.36it/s]


Epoch 331: Avg Training Loss = 0.10290691333220285


Epoch 332/500: 100%|██████████| 16/16 [00:00<00:00, 714.93it/s]


Epoch 332: Avg Training Loss = 0.10320687105002649


Epoch 333/500: 100%|██████████| 16/16 [00:00<00:00, 708.35it/s]


Epoch 333: Avg Training Loss = 0.10523515591836151


Epoch 334/500: 100%|██████████| 16/16 [00:00<00:00, 668.93it/s]


Epoch 334: Avg Training Loss = 0.10375475798569181


Epoch 335/500: 100%|██████████| 16/16 [00:00<00:00, 587.64it/s]


Epoch 335: Avg Training Loss = 0.1040020430844058


Epoch 336/500: 100%|██████████| 16/16 [00:00<00:00, 579.54it/s]


Epoch 336: Avg Training Loss = 0.10172743489965796


Epoch 337/500: 100%|██████████| 16/16 [00:00<00:00, 643.93it/s]


Epoch 337: Avg Training Loss = 0.10206891174482949


Epoch 338/500: 100%|██████████| 16/16 [00:00<00:00, 643.46it/s]


Epoch 338: Avg Training Loss = 0.10663592311389306


Epoch 339/500: 100%|██████████| 16/16 [00:00<00:00, 707.35it/s]


Epoch 339: Avg Training Loss = 0.1049758243812796


Epoch 340/500: 100%|██████████| 16/16 [00:00<00:00, 737.91it/s]


Epoch 340: Avg Training Loss = 0.10928371326778741


Epoch 341/500: 100%|██████████| 16/16 [00:00<00:00, 655.98it/s]


Epoch 341: Avg Training Loss = 0.1023532977218137


Epoch 342/500: 100%|██████████| 16/16 [00:00<00:00, 654.08it/s]


Epoch 342: Avg Training Loss = 0.10150152837912388


Epoch 343/500: 100%|██████████| 16/16 [00:00<00:00, 821.27it/s]


Epoch 343: Avg Training Loss = 0.10521516573670156


Epoch 344/500: 100%|██████████| 16/16 [00:00<00:00, 385.05it/s]


Epoch 344: Avg Training Loss = 0.10507928719744086


Epoch 345/500: 100%|██████████| 16/16 [00:00<00:00, 677.03it/s]


Epoch 345: Avg Training Loss = 0.10302128930411794


Epoch 346/500: 100%|██████████| 16/16 [00:00<00:00, 646.69it/s]


Epoch 346: Avg Training Loss = 0.10858091449036318


Epoch 347/500: 100%|██████████| 16/16 [00:00<00:00, 790.95it/s]


Epoch 347: Avg Training Loss = 0.1115373301812831


Epoch 348/500: 100%|██████████| 16/16 [00:00<00:00, 791.54it/s]


Epoch 348: Avg Training Loss = 0.10234635632813853


Epoch 349/500: 100%|██████████| 16/16 [00:00<00:00, 625.00it/s]


Epoch 349: Avg Training Loss = 0.10348111360936481


Epoch 350/500: 100%|██████████| 16/16 [00:00<00:00, 627.63it/s]


Epoch 350: Avg Training Loss = 0.10293579148128629


Epoch 351/500: 100%|██████████| 16/16 [00:00<00:00, 671.79it/s]


Epoch 351: Avg Training Loss = 0.1029399216229863


Epoch 352/500: 100%|██████████| 16/16 [00:00<00:00, 589.07it/s]


Epoch 352: Avg Training Loss = 0.10723120806848302


Epoch 353/500: 100%|██████████| 16/16 [00:00<00:00, 650.71it/s]


Epoch 353: Avg Training Loss = 0.10545214854509515


Epoch 354/500: 100%|██████████| 16/16 [00:00<00:00, 586.68it/s]


Epoch 354: Avg Training Loss = 0.10384441191768821


Epoch 355/500: 100%|██████████| 16/16 [00:00<00:00, 615.07it/s]


Epoch 355: Avg Training Loss = 0.10575217529035666


Epoch 356/500: 100%|██████████| 16/16 [00:00<00:00, 624.68it/s]


Epoch 356: Avg Training Loss = 0.10678551822681637


Epoch 357/500: 100%|██████████| 16/16 [00:00<00:00, 403.42it/s]


Epoch 357: Avg Training Loss = 0.10411432267659727


Epoch 358/500: 100%|██████████| 16/16 [00:00<00:00, 599.96it/s]


Epoch 358: Avg Training Loss = 0.10455816077506717


Epoch 359/500: 100%|██████████| 16/16 [00:00<00:00, 531.15it/s]


Epoch 359: Avg Training Loss = 0.1044960051008007


Epoch 360/500: 100%|██████████| 16/16 [00:00<00:00, 741.11it/s]


Epoch 360: Avg Training Loss = 0.10431546005694305


Epoch 361/500: 100%|██████████| 16/16 [00:00<00:00, 592.80it/s]


Epoch 361: Avg Training Loss = 0.10715523463509538


Epoch 362/500: 100%|██████████| 16/16 [00:00<00:00, 626.48it/s]


Epoch 362: Avg Training Loss = 0.10325741406311006


Epoch 363/500: 100%|██████████| 16/16 [00:00<00:00, 578.22it/s]


Epoch 363: Avg Training Loss = 0.10432284749934778


Epoch 364/500: 100%|██████████| 16/16 [00:00<00:00, 706.47it/s]


Epoch 364: Avg Training Loss = 0.10329627382623799


Epoch 365/500: 100%|██████████| 16/16 [00:00<00:00, 659.97it/s]


Epoch 365: Avg Training Loss = 0.10290090873947039


Epoch 366/500: 100%|██████████| 16/16 [00:00<00:00, 654.76it/s]


Epoch 366: Avg Training Loss = 0.10709561024080305


Epoch 367/500: 100%|██████████| 16/16 [00:00<00:00, 573.91it/s]


Epoch 367: Avg Training Loss = 0.10333913263371762


Epoch 368/500: 100%|██████████| 16/16 [00:00<00:00, 640.30it/s]


Epoch 368: Avg Training Loss = 0.10506262685007908


Epoch 369/500: 100%|██████████| 16/16 [00:00<00:00, 532.26it/s]


Epoch 369: Avg Training Loss = 0.10539953287362176


Epoch 370/500: 100%|██████████| 16/16 [00:00<00:00, 423.84it/s]


Epoch 370: Avg Training Loss = 0.10435197726987741


Epoch 371/500: 100%|██████████| 16/16 [00:00<00:00, 601.95it/s]


Epoch 371: Avg Training Loss = 0.1031034185879809


Epoch 372/500: 100%|██████████| 16/16 [00:00<00:00, 551.91it/s]


Epoch 372: Avg Training Loss = 0.1021755557945546


Epoch 373/500: 100%|██████████| 16/16 [00:00<00:00, 669.26it/s]


Epoch 373: Avg Training Loss = 0.10597060357823092


Epoch 374/500: 100%|██████████| 16/16 [00:00<00:00, 657.58it/s]


Epoch 374: Avg Training Loss = 0.10189460694570751


Epoch 375/500: 100%|██████████| 16/16 [00:00<00:00, 703.09it/s]


Epoch 375: Avg Training Loss = 0.10318314831923037


Epoch 376/500: 100%|██████████| 16/16 [00:00<00:00, 616.12it/s]


Epoch 376: Avg Training Loss = 0.10674992776201929


Epoch 377/500: 100%|██████████| 16/16 [00:00<00:00, 688.85it/s]


Epoch 377: Avg Training Loss = 0.10962405326940558


Epoch 378/500: 100%|██████████| 16/16 [00:00<00:00, 691.43it/s]


Epoch 378: Avg Training Loss = 0.10913938686580342


Epoch 379/500: 100%|██████████| 16/16 [00:00<00:00, 710.49it/s]


Epoch 379: Avg Training Loss = 0.10338818670853096


Epoch 380/500: 100%|██████████| 16/16 [00:00<00:00, 624.82it/s]


Epoch 380: Avg Training Loss = 0.10344109147348825


Epoch 381/500: 100%|██████████| 16/16 [00:00<00:00, 722.63it/s]


Epoch 381: Avg Training Loss = 0.10733019240090952


Epoch 382/500: 100%|██████████| 16/16 [00:00<00:00, 621.78it/s]


Epoch 382: Avg Training Loss = 0.10311856838491033


Epoch 383/500: 100%|██████████| 16/16 [00:00<00:00, 566.07it/s]


Epoch 383: Avg Training Loss = 0.1063953455647125


Epoch 384/500: 100%|██████████| 16/16 [00:00<00:00, 439.04it/s]


Epoch 384: Avg Training Loss = 0.10139526706188917


Epoch 385/500: 100%|██████████| 16/16 [00:00<00:00, 711.56it/s]


Epoch 385: Avg Training Loss = 0.10292061741518624


Epoch 386/500: 100%|██████████| 16/16 [00:00<00:00, 671.79it/s]


Epoch 386: Avg Training Loss = 0.10732462235233363


Epoch 387/500: 100%|██████████| 16/16 [00:00<00:00, 724.26it/s]


Epoch 387: Avg Training Loss = 0.1032383029403932


Epoch 388/500: 100%|██████████| 16/16 [00:00<00:00, 606.66it/s]


Epoch 388: Avg Training Loss = 0.10272903819842373


Epoch 389/500: 100%|██████████| 16/16 [00:00<00:00, 663.11it/s]


Epoch 389: Avg Training Loss = 0.10414179907563854


Epoch 390/500: 100%|██████████| 16/16 [00:00<00:00, 584.41it/s]


Epoch 390: Avg Training Loss = 0.105025828925564


Epoch 391/500: 100%|██████████| 16/16 [00:00<00:00, 659.35it/s]


Epoch 391: Avg Training Loss = 0.10473030830240425


Epoch 392/500: 100%|██████████| 16/16 [00:00<00:00, 702.12it/s]


Epoch 392: Avg Training Loss = 0.1024207631673883


Epoch 393/500: 100%|██████████| 16/16 [00:00<00:00, 666.83it/s]


Epoch 393: Avg Training Loss = 0.10642559508628704


Epoch 394/500: 100%|██████████| 16/16 [00:00<00:00, 687.88it/s]


Epoch 394: Avg Training Loss = 0.10728726078591802


Epoch 395/500: 100%|██████████| 16/16 [00:00<00:00, 554.95it/s]


Epoch 395: Avg Training Loss = 0.1038675863734063


Epoch 396/500: 100%|██████████| 16/16 [00:00<00:00, 449.70it/s]


Epoch 396: Avg Training Loss = 0.10374944999485332


Epoch 397/500: 100%|██████████| 16/16 [00:00<00:00, 634.26it/s]


Epoch 397: Avg Training Loss = 0.1062494116177892


Epoch 398/500: 100%|██████████| 16/16 [00:00<00:00, 579.12it/s]


Epoch 398: Avg Training Loss = 0.10327628304195755


Epoch 399/500: 100%|██████████| 16/16 [00:00<00:00, 591.12it/s]


Epoch 399: Avg Training Loss = 0.10286392928922877


Epoch 400/500: 100%|██████████| 16/16 [00:00<00:00, 641.67it/s]


Epoch 400: Avg Training Loss = 0.10159937462166828


Epoch 401/500: 100%|██████████| 16/16 [00:00<00:00, 566.23it/s]


Epoch 401: Avg Training Loss = 0.1028867816169034


Epoch 402/500: 100%|██████████| 16/16 [00:00<00:00, 608.66it/s]


Epoch 402: Avg Training Loss = 0.10841213169452898


Epoch 403/500: 100%|██████████| 16/16 [00:00<00:00, 654.80it/s]


Epoch 403: Avg Training Loss = 0.1050601247971987


Epoch 404/500: 100%|██████████| 16/16 [00:00<00:00, 645.69it/s]


Epoch 404: Avg Training Loss = 0.1077528047539732


Epoch 405/500: 100%|██████████| 16/16 [00:00<00:00, 521.76it/s]


Epoch 405: Avg Training Loss = 0.10184675652314634


Epoch 406/500: 100%|██████████| 16/16 [00:00<00:00, 648.40it/s]


Epoch 406: Avg Training Loss = 0.10582324980265077


Epoch 407/500: 100%|██████████| 16/16 [00:00<00:00, 774.89it/s]


Epoch 407: Avg Training Loss = 0.10232798926367917


Epoch 408/500: 100%|██████████| 16/16 [00:00<00:00, 382.51it/s]


Epoch 408: Avg Training Loss = 0.10170040865812231


Epoch 409/500: 100%|██████████| 16/16 [00:00<00:00, 630.49it/s]


Epoch 409: Avg Training Loss = 0.10605899584205712


Epoch 410/500: 100%|██████████| 16/16 [00:00<00:00, 477.61it/s]


Epoch 410: Avg Training Loss = 0.1095022991683115


Epoch 411/500: 100%|██████████| 16/16 [00:00<00:00, 484.44it/s]


Epoch 411: Avg Training Loss = 0.11031102375401293


Epoch 412/500: 100%|██████████| 16/16 [00:00<00:00, 543.19it/s]


Epoch 412: Avg Training Loss = 0.10255903704091907


Epoch 413/500: 100%|██████████| 16/16 [00:00<00:00, 645.86it/s]


Epoch 413: Avg Training Loss = 0.10148412613745998


Epoch 414/500: 100%|██████████| 16/16 [00:00<00:00, 649.88it/s]


Epoch 414: Avg Training Loss = 0.10243924827698399


Epoch 415/500: 100%|██████████| 16/16 [00:00<00:00, 617.59it/s]


Epoch 415: Avg Training Loss = 0.10240268066306324


Epoch 416/500: 100%|██████████| 16/16 [00:00<00:00, 672.30it/s]


Epoch 416: Avg Training Loss = 0.10383513599962872


Epoch 417/500: 100%|██████████| 16/16 [00:00<00:00, 604.95it/s]


Epoch 417: Avg Training Loss = 0.10413334032465868


Epoch 418/500: 100%|██████████| 16/16 [00:00<00:00, 636.83it/s]


Epoch 418: Avg Training Loss = 0.10200133714277078


Epoch 419/500: 100%|██████████| 16/16 [00:00<00:00, 733.10it/s]


Epoch 419: Avg Training Loss = 0.10451542679220438


Epoch 420/500: 100%|██████████| 16/16 [00:00<00:00, 387.24it/s]


Epoch 420: Avg Training Loss = 0.11272707102162872


Epoch 421/500: 100%|██████████| 16/16 [00:00<00:00, 798.97it/s]


Epoch 421: Avg Training Loss = 0.10064870193052818


Epoch 422/500: 100%|██████████| 16/16 [00:00<00:00, 663.85it/s]


Epoch 422: Avg Training Loss = 0.1055284125785179


Epoch 423/500: 100%|██████████| 16/16 [00:00<00:00, 712.58it/s]


Epoch 423: Avg Training Loss = 0.10251877062460955


Epoch 424/500: 100%|██████████| 16/16 [00:00<00:00, 689.58it/s]


Epoch 424: Avg Training Loss = 0.10462391579194981


Epoch 425/500: 100%|██████████| 16/16 [00:00<00:00, 719.93it/s]


Epoch 425: Avg Training Loss = 0.10194833787596401


Epoch 426/500: 100%|██████████| 16/16 [00:00<00:00, 670.18it/s]


Epoch 426: Avg Training Loss = 0.10217876777545933


Epoch 427/500: 100%|██████████| 16/16 [00:00<00:00, 655.55it/s]


Epoch 427: Avg Training Loss = 0.11299606553717133


Epoch 428/500: 100%|██████████| 16/16 [00:00<00:00, 797.76it/s]


Epoch 428: Avg Training Loss = 0.0987813968129237


Epoch 429/500: 100%|██████████| 16/16 [00:00<00:00, 620.04it/s]


Epoch 429: Avg Training Loss = 0.10440065799390569


Epoch 430/500: 100%|██████████| 16/16 [00:00<00:00, 669.06it/s]


Epoch 430: Avg Training Loss = 0.1026284192031359


Epoch 431/500: 100%|██████████| 16/16 [00:00<00:00, 374.61it/s]


Epoch 431: Avg Training Loss = 0.10398019595509943


Epoch 432/500: 100%|██████████| 16/16 [00:00<00:00, 500.44it/s]


Epoch 432: Avg Training Loss = 0.10220409023082432


Epoch 433/500: 100%|██████████| 16/16 [00:00<00:00, 620.78it/s]


Epoch 433: Avg Training Loss = 0.10521384153295965


Epoch 434/500: 100%|██████████| 16/16 [00:00<00:00, 625.29it/s]


Epoch 434: Avg Training Loss = 0.10190390905036646


Epoch 435/500: 100%|██████████| 16/16 [00:00<00:00, 588.07it/s]


Epoch 435: Avg Training Loss = 0.10300106385394055


Epoch 436/500: 100%|██████████| 16/16 [00:00<00:00, 589.78it/s]


Epoch 436: Avg Training Loss = 0.10296708890510832


Epoch 437/500: 100%|██████████| 16/16 [00:00<00:00, 587.46it/s]


Epoch 437: Avg Training Loss = 0.11115511975196354


Epoch 438/500: 100%|██████████| 16/16 [00:00<00:00, 649.29it/s]


Epoch 438: Avg Training Loss = 0.10280262424117502


Epoch 439/500: 100%|██████████| 16/16 [00:00<00:00, 620.40it/s]


Epoch 439: Avg Training Loss = 0.10346956723643576


Epoch 440/500: 100%|██████████| 16/16 [00:00<00:00, 665.70it/s]


Epoch 440: Avg Training Loss = 0.10270152356037322


Epoch 441/500: 100%|██████████| 16/16 [00:00<00:00, 672.34it/s]


Epoch 441: Avg Training Loss = 0.10964320884907947


Epoch 442/500: 100%|██████████| 16/16 [00:00<00:00, 738.59it/s]


Epoch 442: Avg Training Loss = 0.10201312461867929


Epoch 443/500: 100%|██████████| 16/16 [00:00<00:00, 675.30it/s]


Epoch 443: Avg Training Loss = 0.10332182934507728


Epoch 444/500: 100%|██████████| 16/16 [00:00<00:00, 679.80it/s]


Epoch 444: Avg Training Loss = 0.10546504402094904


Epoch 445/500: 100%|██████████| 16/16 [00:00<00:00, 386.39it/s]


Epoch 445: Avg Training Loss = 0.10345154548721279


Epoch 446/500: 100%|██████████| 16/16 [00:00<00:00, 566.00it/s]


Epoch 446: Avg Training Loss = 0.10403711540514932


Epoch 447/500: 100%|██████████| 16/16 [00:00<00:00, 561.11it/s]


Epoch 447: Avg Training Loss = 0.1033725849188426


Epoch 448/500: 100%|██████████| 16/16 [00:00<00:00, 510.93it/s]


Epoch 448: Avg Training Loss = 0.10883266637649607


Epoch 449/500: 100%|██████████| 16/16 [00:00<00:00, 616.23it/s]


Epoch 449: Avg Training Loss = 0.10432264852501891


Epoch 450/500: 100%|██████████| 16/16 [00:00<00:00, 623.94it/s]


Epoch 450: Avg Training Loss = 0.1032820711569751


Epoch 451/500: 100%|██████████| 16/16 [00:00<00:00, 697.66it/s]


Epoch 451: Avg Training Loss = 0.10321322305347114


Epoch 452/500: 100%|██████████| 16/16 [00:00<00:00, 627.65it/s]


Epoch 452: Avg Training Loss = 0.10270035773625269


Epoch 453/500: 100%|██████████| 16/16 [00:00<00:00, 751.17it/s]


Epoch 453: Avg Training Loss = 0.10204752712674878


Epoch 454/500: 100%|██████████| 16/16 [00:00<00:00, 677.14it/s]


Epoch 454: Avg Training Loss = 0.1040207174990107


Epoch 455/500: 100%|██████████| 16/16 [00:00<00:00, 614.51it/s]


Epoch 455: Avg Training Loss = 0.10344360801665221


Epoch 456/500: 100%|██████████| 16/16 [00:00<00:00, 607.30it/s]


Epoch 456: Avg Training Loss = 0.10379362648681682


Epoch 457/500: 100%|██████████| 16/16 [00:00<00:00, 591.74it/s]


Epoch 457: Avg Training Loss = 0.10518797050120637


Epoch 458/500: 100%|██████████| 16/16 [00:00<00:00, 576.65it/s]


Epoch 458: Avg Training Loss = 0.10675806705566014


Epoch 459/500: 100%|██████████| 16/16 [00:00<00:00, 542.11it/s]


Epoch 459: Avg Training Loss = 0.1030008625376093


Epoch 460/500: 100%|██████████| 16/16 [00:00<00:00, 694.67it/s]


Epoch 460: Avg Training Loss = 0.10226954999105896


Epoch 461/500: 100%|██████████| 16/16 [00:00<00:00, 658.58it/s]


Epoch 461: Avg Training Loss = 0.1123462913229185


Epoch 462/500: 100%|██████████| 16/16 [00:00<00:00, 562.68it/s]


Epoch 462: Avg Training Loss = 0.11070657176349093


Epoch 463/500: 100%|██████████| 16/16 [00:00<00:00, 470.17it/s]


Epoch 463: Avg Training Loss = 0.10645067965721383


Epoch 464/500: 100%|██████████| 16/16 [00:00<00:00, 480.69it/s]


Epoch 464: Avg Training Loss = 0.10551100279040196


Epoch 465/500: 100%|██████████| 16/16 [00:00<00:00, 769.84it/s]


Epoch 465: Avg Training Loss = 0.10449582949171171


Epoch 466/500: 100%|██████████| 16/16 [00:00<00:00, 734.76it/s]


Epoch 466: Avg Training Loss = 0.1050485303515897


Epoch 467/500: 100%|██████████| 16/16 [00:00<00:00, 810.51it/s]


Epoch 467: Avg Training Loss = 0.10324566016959794


Epoch 468/500: 100%|██████████| 16/16 [00:00<00:00, 667.83it/s]


Epoch 468: Avg Training Loss = 0.10360689422882655


Epoch 469/500: 100%|██████████| 16/16 [00:00<00:00, 695.54it/s]


Epoch 469: Avg Training Loss = 0.10330848639611812


Epoch 470/500: 100%|██████████| 16/16 [00:00<00:00, 566.01it/s]


Epoch 470: Avg Training Loss = 0.1032931953394676


Epoch 471/500: 100%|██████████| 16/16 [00:00<00:00, 596.79it/s]


Epoch 471: Avg Training Loss = 0.10376909057445385


Epoch 472/500: 100%|██████████| 16/16 [00:00<00:00, 695.83it/s]


Epoch 472: Avg Training Loss = 0.10304296126260477


Epoch 473/500: 100%|██████████| 16/16 [00:00<00:00, 729.91it/s]


Epoch 473: Avg Training Loss = 0.10347945002071998


Epoch 474/500: 100%|██████████| 16/16 [00:00<00:00, 792.28it/s]


Epoch 474: Avg Training Loss = 0.1051640884457704


Epoch 475/500: 100%|██████████| 16/16 [00:00<00:00, 643.57it/s]


Epoch 475: Avg Training Loss = 0.10164508533061427


Epoch 476/500: 100%|██████████| 16/16 [00:00<00:00, 546.18it/s]


Epoch 476: Avg Training Loss = 0.10837471055086045


Epoch 477/500: 100%|██████████| 16/16 [00:00<00:00, 580.91it/s]


Epoch 477: Avg Training Loss = 0.11638489310794017


Epoch 478/500: 100%|██████████| 16/16 [00:00<00:00, 579.90it/s]


Epoch 478: Avg Training Loss = 0.10491867730503573


Epoch 479/500: 100%|██████████| 16/16 [00:00<00:00, 546.68it/s]


Epoch 479: Avg Training Loss = 0.10401425431208576


Epoch 480/500: 100%|██████████| 16/16 [00:00<00:00, 670.13it/s]


Epoch 480: Avg Training Loss = 0.10384014233782449


Epoch 481/500: 100%|██████████| 16/16 [00:00<00:00, 754.63it/s]


Epoch 481: Avg Training Loss = 0.10350599975379951


Epoch 482/500: 100%|██████████| 16/16 [00:00<00:00, 727.14it/s]


Epoch 482: Avg Training Loss = 0.1036189111387905


Epoch 483/500: 100%|██████████| 16/16 [00:00<00:00, 801.80it/s]


Epoch 483: Avg Training Loss = 0.10266246583641452


Epoch 484/500: 100%|██████████| 16/16 [00:00<00:00, 678.67it/s]


Epoch 484: Avg Training Loss = 0.1037518790758708


Epoch 485/500: 100%|██████████| 16/16 [00:00<00:00, 751.25it/s]


Epoch 485: Avg Training Loss = 0.10444121739334043


Epoch 486/500: 100%|██████████| 16/16 [00:00<00:00, 609.78it/s]


Epoch 486: Avg Training Loss = 0.1048888630398056


Epoch 487/500: 100%|██████████| 16/16 [00:00<00:00, 709.79it/s]


Epoch 487: Avg Training Loss = 0.10448069273329832


Epoch 488/500: 100%|██████████| 16/16 [00:00<00:00, 720.88it/s]


Epoch 488: Avg Training Loss = 0.10260131099151776


Epoch 489/500: 100%|██████████| 16/16 [00:00<00:00, 733.19it/s]


Epoch 489: Avg Training Loss = 0.10382361983989968


Epoch 490/500: 100%|██████████| 16/16 [00:00<00:00, 716.91it/s]


Epoch 490: Avg Training Loss = 0.10348309247809298


Epoch 491/500: 100%|██████████| 16/16 [00:00<00:00, 689.53it/s]


Epoch 491: Avg Training Loss = 0.10538930938962628


Epoch 492/500: 100%|██████████| 16/16 [00:00<00:00, 556.64it/s]


Epoch 492: Avg Training Loss = 0.1064202115213608


Epoch 493/500: 100%|██████████| 16/16 [00:00<00:00, 692.50it/s]


Epoch 493: Avg Training Loss = 0.10359668794690687


Epoch 494/500: 100%|██████████| 16/16 [00:00<00:00, 701.32it/s]


Epoch 494: Avg Training Loss = 0.1021879804046715


Epoch 495/500: 100%|██████████| 16/16 [00:00<00:00, 723.92it/s]


Epoch 495: Avg Training Loss = 0.10230877650353838


Epoch 496/500: 100%|██████████| 16/16 [00:00<00:00, 652.24it/s]


Epoch 496: Avg Training Loss = 0.10241751022198621


Epoch 497/500: 100%|██████████| 16/16 [00:00<00:00, 703.94it/s]


Epoch 497: Avg Training Loss = 0.10558733344078064


Epoch 498/500: 100%|██████████| 16/16 [00:00<00:00, 621.99it/s]


Epoch 498: Avg Training Loss = 0.10462832927484722


Epoch 499/500: 100%|██████████| 16/16 [00:00<00:00, 704.16it/s]


Epoch 499: Avg Training Loss = 0.10542576732661794


Epoch 500/500: 100%|██████████| 16/16 [00:00<00:00, 730.01it/s]

Epoch 500: Avg Training Loss = 0.10138328729526085


In [14]:
y_std_d = y_std.to(device)
y_mean_d = y_mean.to(device)

for x, y in test_loader:
    x_d = x.to(device)
    y_d = y.to(device)
    pred = model(x_d)
    
    pred = (pred * y_std_d) + y_mean_d
    y_d = (y_d * y_std_d) + y_mean_d
    
    print(torch.abs(pred - y_d)[0])
    

tensor([ 1.2387, 78.9792], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([35.1387, 24.1208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([33.1387, 78.0208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([37.2613, 21.9792], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([64.1387,  7.2792], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([74.1387, 50.5208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([93.7387, 97.7208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([60.4387,  1.3208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([26.3387, 58.7208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([91.7613, 87.7208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([19.7387, 14.6792], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([ 48.7613, 125.0792], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([46.1387, 64.7208], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([ 99.3387, 148.2208], device='cuda:0', grad_fn=<SelectBackward0>)
te